CREATE USER IF NOT EXISTS "admin"@'%' IDENTIFIED BY "admin123";

CREATE DATABASE IF NOT EXISTS myproject;

ALTER DATABASE myproject
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON myproject.* TO 'admin'@'%' IDENTIFIED BY 'admin123';
